// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQL3GHqo9iWLjNdp3faNNLuOkFlKIKfM',
    appId: '1:694876792779:web:dfa99da9599905f7adb84e',
    messagingSenderId: '694876792779',
    projectId: 'flojics-task-b15ad',
    authDomain: 'flojics-task-b15ad.firebaseapp.com',
    storageBucket: 'flojics-task-b15ad.appspot.com',
    measurementId: 'G-7GLE38BGRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhWbc0VcABD5KEkp-Q1NnAAJ2XWzymQLY',
    appId: '1:694876792779:android:f2dfb61d48d2fdafadb84e',
    messagingSenderId: '694876792779',
    projectId: 'flojics-task-b15ad',
    storageBucket: 'flojics-task-b15ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzrL94UbIXwqwtu-teWoofP2WOJCxVfcU',
    appId: '1:694876792779:ios:7cb8a6ae7c413a03adb84e',
    messagingSenderId: '694876792779',
    projectId: 'flojics-task-b15ad',
    storageBucket: 'flojics-task-b15ad.appspot.com',
    iosBundleId: 'com.example.flojicsTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzrL94UbIXwqwtu-teWoofP2WOJCxVfcU',
    appId: '1:694876792779:ios:7a3e733e657e8f2cadb84e',
    messagingSenderId: '694876792779',
    projectId: 'flojics-task-b15ad',
    storageBucket: 'flojics-task-b15ad.appspot.com',
    iosBundleId: 'com.example.flojicsTask.RunnerTests',
  );
}
